baseURL = 'https://noumenalnotions.space'
languageCode = 'en-us'
title = 'Noumenal Notions'
theme = 'terminal'
publishDir = 'docs'


[[menu.main]]
identifier = "blogs"
name = "Blog"
url = "/blogs/"
weight = 1

[[menu.main]]
identifier = "essays"
name = "Essays"
url = "/essays/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "poetry"
name = "Poetry"
url = "/poetry/"
weight = 1

[[menu.main]]
identifier = "software"
name = "Software"
url = "/software/"
weight = 1

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 99

[params] 
themeColor = "red"
showMenuItems = 6
mainSections = [ "blogs", "essays", "poetry", "about" ]
autoCover = true
favicon = "favicon.ico"
readingTime = true


[languages.en.params.logo]
logoText = "Noumenal Notions"
logoHomeLink = "/"
